// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class Main {
    public static void main(String[] args) {
        int i = 2, x = 1, y = 0, sum = 0;

        while (i > 0) {
            int fibTemp = x + y;
            y = x;
            x = fibTemp;
            if (fibTemp % 2 == 0 && sum < 4000000) {
                sum = sum + fibTemp;

            }
            i++;
        }
        System.out.println(sum);
    }
}

// ans: 4613732
