/*
Problem Statement: You are given two strings s and t.
                   String t is generated by random shuffling string s and then add one more letter at a random position.
                   Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

Example 3:

Input: s = "a", t = "aa"
Output: "a"

Example 4:

Input: s = "ae", t = "aea"
Output: "a"

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lower-case English letters.

Expected Time Complexity: O(n)
Expected Auxiliary Space: constant

*/


// Driver code starts

#include "bits/stdc++.h"
#define endl "\n"

using namespace std;


char findTheDifference(string s, string t) {
  int count[26] = {0};
  for (auto x : t) {
    count[x - 'a']++;
  }
  for (auto x : s) {
    count[x - 'a']--;
  }
  for (int i = 0; i < 26; i++) {
    if (count[i] == 1) {
      return char(97 + i);
    }
  }
  return ' ';
}


int main()
{
  int t;
  cin >> t;
  while (t--)
  {
    string s, t;
    cin >> s >> t;
    cout << findTheDifference(s, t) << endl;
  }
  return 0;
}

